### PR TITLE
show methods

### PR DESCRIPTION
**Pull request by TeroFrondelius**
Here is the updated usage example:
```julia
julia> b = load("data/libBehaviour.so","Norton", mbv.Tridimensional)
behaviour Norton in shared library data/libBehaviour.so for modelling hypothesis Tridimensional generated from Norton.mfront using TFEL version: 3.3.0-dev.

julia> d = BehaviourData(b)
MFrontInterface.behaviour.BehaviourDataAllocated(Ptr{Nothing} @0x0000000002a50610)

julia> get_internal_state_variables(get_initial_state(d))
7-element RealsVector
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0


julia> get_parameters(b)
11-element StringsVector
 epsilon
 YoungModulus
 PoissonRatio
 RelativeValueForTheEquivalentStressLowerBoundDefinition
 K
 E
 A
 minimal_time_step_scaling_factor
 maximal_time_step_scaling_factor
 theta
 numerical_jacobian_epsilon


julia> get_external_state_variables(b)
1-element VariablesVector
 Temperature


julia> 

```

@thelfer here is an example of overloading `Base.show` function to get nicer interactive user experience. You know the internals better, is there something we should add or remove? I would like to use `get_parameters`, but I couldn't figured out how to use it. Can you help me creating another method for another type?

### CODE REVIEW

**Comment by TeroFrondelius** [comment]
@IvanYashchuk let's focus the MFront Julia development in this package. I'm using this package to connect MFront to JuliaFEM. If you already experienced it would be really cool to get you onboard developing this further. Please feel free to open issues/pull request to get the development forward.

**Comment by thelfer** [comment]
@TeroFrondelius Sorry for the delay. Does `Base.show` provide a short or detailled description of the object ? If it is a short description, then I would somehow invert the first and second line as follows:

~~~~
julia> b = load("data/libBehaviour.so","ParameterTest", mbv.Tridimensional)
behaviour ParameterTest in shared library Behaviour for modelling hypothesis Tridimensional
generated from ParameterTest.mfront using TFEL version: 3.3.0-dev
~~~~

If a detailled description is more suitable, one shall discuss this because a detailled description can be quite long.. 

Thomas

**Comment by TeroFrondelius** [comment]
> Does `Base.show` provide a short or detailled description of the object ?

I think the possibilities are endless. Here are some examples: https://docs.julialang.org/en/v1/base/io-network/#Base.IOContext. I don't have earlier experience, but my idea is to make user interactive usage as easy and intuitive as possible.

**Comment by TeroFrondelius** [comment]
@thelfer what method I should use to dick into the `BehaviourDataAllocated`? I think it would be cool to show something in this first version, we can make it perfect later on.

**Comment by thelfer** [comment]
@TeroFrondelius BehaviourData is nothing really interesting per se.
I would simply write:

~~~~
data associated with behavior <name of the behaviour> in library <...>
~~~~

The name of the behaviour can be retrieved for the behaviour object

**Comment by TeroFrondelius** [comment]
> @TeroFrondelius BehaviourData is nothing really interesting per se.
> I would simply write:
> 
> ```
> data associated with behavior <name of the behaviour> in library <...>
> ```
> 
> The name of the behaviour can be retrieved for the behaviour object

I would eventually like to build a way to dig the data interactively in the REPL session. As an example, instead of writing:
```julia
julia> get_internal_state_variables(get_initial_state(d))
7-element RealsVector
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
```
Maybe we should have something like this:
```julia
julia> d.internal_state_variables[0]
7-element RealsVector, time = 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
```

Thus in my mind printing the BehaviourData structure would help users/developers to more easily understand the data model and its usage.

**Comment by IvanYashchuk** [comment]
> Maybe we should have something like this:
> 
> ```julia
> julia> d.internal_state_variables[0]
> 7-element RealsVector, time = 0.0
>  0.0
>  0.0
>  0.0
>  0.0
>  0.0
>  0.0
>  0.0
> ```

It seems that this kind of functionality is not yet implemented in CxxWrap.jl
https://github.com/JuliaInterop/CxxWrap.jl/issues/90

**Comment by TeroFrondelius** [comment]
I merged these changes. If I will do more show methods I will open a new pull request.

**Pull request merged**
